# Generated by Django 5.2.9 on 2025-12-15 05:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("WINDOW", "Window"),
                            ("DOOR", "Door"),
                            ("FORTOCHKA", "Fortochka"),
                        ],
                        max_length=32,
                        verbose_name="Order type",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Order number"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(verbose_name="Order quantity"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        verbose_name="Order's total price",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        verbose_name="Cost price of order",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        verbose_name="Profit from the order",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=11,
                        null=True,
                        verbose_name="Discount price",
                    ),
                ),
                (
                    "advance_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=11, verbose_name="Advance payment"
                    ),
                ),
                (
                    "order_owner",
                    models.CharField(max_length=64, verbose_name="Owner name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+998\\d{9}$"
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                ("location", models.TextField(verbose_name="Location")),
                ("additional_info", models.TextField(verbose_name="Additional info")),
            ],
            options={
                "verbose_name": "New Order",
                "verbose_name_plural": "New Orders",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "total_orders_number",
                    models.PositiveIntegerField(verbose_name="Total number of orders"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        verbose_name="Total price of orders",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("CLOSED", "Closed"),
                            ("IN_PROCESS", "In_process"),
                            ("IN_DEBT", "In_debt"),
                        ],
                        default="WAITING",
                        max_length=32,
                        verbose_name="Order status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("height_size", models.FloatField(verbose_name="Order's height size")),
                ("width_size", models.FloatField(verbose_name="Order's width size")),
                (
                    "include_waster_percentage",
                    models.BooleanField(
                        default=True, verbose_name="Include waste percentage"
                    ),
                ),
                (
                    "waste_percentage",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Waste percentage"
                    ),
                ),
                (
                    "has_balcony",
                    models.BooleanField(default=False, verbose_name="Order's balcony"),
                ),
                (
                    "has_metal",
                    models.BooleanField(default=False, verbose_name="Order's metal"),
                ),
                (
                    "metal_thickness",
                    models.CharField(
                        blank=True,
                        choices=[("1.0 mm", "1.0 mm"), ("1.2 mm", "1.2 mm")],
                        max_length=32,
                        null=True,
                        verbose_name="Metal thickness",
                    ),
                ),
                ("shelf_width", models.FloatField(verbose_name="Shelf width")),
                (
                    "has_handle",
                    models.BooleanField(default=False, verbose_name="Order handle"),
                ),
                (
                    "design_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.designoption",
                        verbose_name="Order design option",
                    ),
                ),
                (
                    "design_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.designvariant",
                        verbose_name="Order design variant",
                    ),
                ),
                (
                    "frame_profile_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.frameprofiltype",
                        verbose_name="Frame profil type",
                    ),
                ),
                (
                    "glass_layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.glasslayer",
                        verbose_name="Order's glass layer",
                    ),
                ),
                (
                    "glass_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.glasstype",
                        verbose_name="Order's glass type",
                    ),
                ),
                (
                    "handle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.handletype",
                        verbose_name="Order's handle type",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.materialtype",
                        verbose_name="Order material",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_detail",
                        to="orders.neworder",
                        verbose_name="Main order",
                    ),
                ),
                (
                    "profil_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.profiltype",
                        verbose_name="Order's profil type",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="company.provider",
                        verbose_name="Provider",
                    ),
                ),
                (
                    "sash_profil_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.sashprofiltype",
                        verbose_name="Sash profil type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Detail",
                "verbose_name_plural": "Order Details",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Template name",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("WINDOW", "Window"),
                            ("DOOR", "Door"),
                            ("FORTOCHKA", "Fortochka"),
                        ],
                        max_length=32,
                        verbose_name="Template type",
                    ),
                ),
                (
                    "base_width_mm",
                    models.PositiveIntegerField(verbose_name="Base width"),
                ),
                (
                    "base_height_mm",
                    models.PositiveSmallIntegerField(verbose_name="Base height"),
                ),
                (
                    "base_price_per_m2",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Window/Door/Fortochka's base price per m2.",
                        max_digits=10,
                        verbose_name="Base price",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "template_type"),
                        name="unique_name_per_template_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DoorOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "width_mm",
                    models.PositiveIntegerField(verbose_name="Order's width size."),
                ),
                (
                    "height_mm",
                    models.PositiveIntegerField(verbose_name="Order's height size."),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Order's total price",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.template",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Door Order",
                "verbose_name_plural": "Door Orders",
            },
        ),
        migrations.CreateModel(
            name="TemplateSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "has_glass",
                    models.BooleanField(default=True, verbose_name="Has section glass"),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("TOP", "Top"),
                            ("MIDDLE", "Middle"),
                            ("BOTTOM", "Bottom"),
                        ],
                        max_length=32,
                        verbose_name="Section type",
                    ),
                ),
                (
                    "section_order",
                    models.PositiveIntegerField(verbose_name="Section order number"),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("VERTICAL", "Vertical"),
                            ("HORIZONTAL", "Horizontal"),
                        ],
                        max_length=15,
                        verbose_name="Orientation type",
                    ),
                ),
                (
                    "width_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Section's width size"
                    ),
                ),
                (
                    "height_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Section's height size"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="orders.template",
                        verbose_name="Related template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Section",
                "verbose_name_plural": "Template Sections",
            },
        ),
        migrations.CreateModel(
            name="DoorOrderSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "section_order",
                    models.PositiveIntegerField(verbose_name="Section order number"),
                ),
                (
                    "width_mm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Section width in mm"
                    ),
                ),
                (
                    "height_mm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Section height in mm"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="door_sections",
                        to="orders.doororder",
                        verbose_name="Related order",
                    ),
                ),
                (
                    "template_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="door_order_sections",
                        to="orders.templatesection",
                        verbose_name="Original template section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Door order section",
                "verbose_name_plural": "Door order sections",
            },
        ),
        migrations.CreateModel(
            name="WindowOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "width_mm",
                    models.PositiveIntegerField(verbose_name="Order's width size."),
                ),
                (
                    "height_mm",
                    models.PositiveIntegerField(verbose_name="Order's height size."),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Order's total price",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.template",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Window Order",
                "verbose_name_plural": "Window Orders",
            },
        ),
        migrations.CreateModel(
            name="WindowOrderSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "section_order",
                    models.PositiveIntegerField(verbose_name="Section order number"),
                ),
                (
                    "width_mm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Section width in mm"
                    ),
                ),
                (
                    "height_mm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Section height in mm"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="orders.windoworder",
                        verbose_name="Related order",
                    ),
                ),
                (
                    "template_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_sections",
                        to="orders.templatesection",
                        verbose_name="Original template section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Window order section",
                "verbose_name_plural": "Window order sections",
            },
        ),
    ]
