# Generated by Django 5.2.9 on 2025-12-05 05:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("WINDOW", "Window"),
                            ("DOOR", "Door"),
                            ("FORTOCHKA", "Fortochka"),
                        ],
                        max_length=32,
                        verbose_name="Order type",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Order number"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(verbose_name="Order quantity"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        verbose_name="Order's total price",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        verbose_name="Cost price of order",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        verbose_name="Profit from the order",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=11,
                        null=True,
                        verbose_name="Discount price",
                    ),
                ),
                (
                    "advance_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=11, verbose_name="Advance payment"
                    ),
                ),
                (
                    "order_owner",
                    models.CharField(max_length=64, verbose_name="Owner name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+998\\d{9}$"
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                ("location", models.TextField(verbose_name="Location")),
                ("additional_info", models.TextField(verbose_name="Additional info")),
            ],
            options={
                "verbose_name": "New Order",
                "verbose_name_plural": "New Orders",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "total_orders_number",
                    models.PositiveIntegerField(verbose_name="Total number of orders"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        verbose_name="Total price of orders",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("CLOSED", "Closed"),
                            ("IN_PROCESS", "In_process"),
                            ("IN_DEBT", "In_debt"),
                        ],
                        default="WAITING",
                        max_length=32,
                        verbose_name="Order status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("height_size", models.FloatField(verbose_name="Order's height size")),
                ("width_size", models.FloatField(verbose_name="Order's width size")),
                (
                    "include_waster_percentage",
                    models.BooleanField(
                        default=True, verbose_name="Include waste percentage"
                    ),
                ),
                (
                    "waste_percentage",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Waste percentage"
                    ),
                ),
                (
                    "has_balcony",
                    models.BooleanField(default=False, verbose_name="Order's balcony"),
                ),
                (
                    "has_metal",
                    models.BooleanField(default=False, verbose_name="Order's metal"),
                ),
                (
                    "metal_thickness",
                    models.CharField(
                        blank=True,
                        choices=[("1.0 mm", "1.0 mm"), ("1.2 mm", "1.2 mm")],
                        max_length=32,
                        null=True,
                        verbose_name="Metal thickness",
                    ),
                ),
                ("shelf_width", models.FloatField(verbose_name="Shelf width")),
                (
                    "has_handle",
                    models.BooleanField(default=False, verbose_name="Order handle"),
                ),
                (
                    "design_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.designoption",
                        verbose_name="Order design option",
                    ),
                ),
                (
                    "design_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.designvariant",
                        verbose_name="Order design variant",
                    ),
                ),
                (
                    "frame_profile_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.frameprofiltype",
                        verbose_name="Frame profil type",
                    ),
                ),
                (
                    "glass_layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.glasslayer",
                        verbose_name="Order's glass layer",
                    ),
                ),
                (
                    "glass_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.glasstype",
                        verbose_name="Order's glass type",
                    ),
                ),
                (
                    "handle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.handletype",
                        verbose_name="Order's handle type",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.materialtype",
                        verbose_name="Order material",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_detail",
                        to="orders.neworder",
                        verbose_name="Main order",
                    ),
                ),
                (
                    "profil_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.profiltype",
                        verbose_name="Order's profil type",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="company.provider",
                        verbose_name="Provider",
                    ),
                ),
                (
                    "sash_profil_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="materials.sashprofiltype",
                        verbose_name="Sash profil type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Detail",
                "verbose_name_plural": "Order Details",
            },
        ),
    ]
