# Generated by Django 5.2.9 on 2025-12-09 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Template name"),
                ),
                (
                    "base_width_mm",
                    models.PositiveIntegerField(verbose_name="Base width"),
                ),
                (
                    "base_height_mm",
                    models.PositiveSmallIntegerField(verbose_name="Base height"),
                ),
                (
                    "base_price_per_m2",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Window's base price per m2.",
                        max_digits=10,
                        verbose_name="Base price",
                    ),
                ),
            ],
            options={
                "verbose_name": "Window Template",
                "verbose_name_plural": "Window Templates",
            },
        ),
        migrations.CreateModel(
            name="WindowOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "width_mm",
                    models.PositiveIntegerField(verbose_name="Order's width size."),
                ),
                (
                    "height_mm",
                    models.PositiveIntegerField(verbose_name="Order's height size."),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Order's total price",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.windowtemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "section_order",
                    models.PositiveIntegerField(verbose_name="Section order number"),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("vertical", "Vertical"),
                            ("horizontal", "Horizontal"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "width_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Section's width size"
                    ),
                ),
                (
                    "height_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Section's height size"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="orders.windowtemplate",
                        verbose_name="Related template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Section",
                "verbose_name_plural": "Template Sections",
            },
        ),
    ]
