# Generated by Django 5.2.9 on 2025-12-16 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="window_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="window_detail",
                to="orders.windoworder",
                verbose_name="Window order detail",
            ),
        ),
        migrations.AlterField(
            model_name="templatesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("TOP", "Top"),
                    ("MIDDLE", "Middle"),
                    ("BOTTOM", "Bottom"),
                    ("WHOLE", "Whole"),
                ],
                max_length=32,
                verbose_name="Section type",
            ),
        ),
    ]
