# Generated by Django 5.2.9 on 2025-12-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_windowtemplate_windoworder_templatesection"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindowOrderSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "section_order",
                    models.PositiveIntegerField(verbose_name="Section order number"),
                ),
                (
                    "width_mm",
                    models.PositiveIntegerField(verbose_name="Section width in mm"),
                ),
                (
                    "height_mm",
                    models.PositiveIntegerField(verbose_name="Section height in mm"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="orders.windoworder",
                        verbose_name="Related order",
                    ),
                ),
                (
                    "template_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_sections",
                        to="orders.templatesection",
                        verbose_name="Original template section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Window order section",
                "verbose_name_plural": "Window order sections",
                "ordering": ["section_order"],
            },
        ),
    ]
