# Generated by Django 5.2.9 on 2025-12-16 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orderdetail_window_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="height_size",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="width_size",
        ),
    ]
