# Generated by Django 5.2.9 on 2025-12-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_windowordersection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windowordersection",
            name="height_mm",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Section height in mm"
            ),
        ),
        migrations.AlterField(
            model_name="windowordersection",
            name="width_mm",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Section width in mm"
            ),
        ),
        migrations.AlterField(
            model_name="windowtemplate",
            name="name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Template name"
            ),
        ),
    ]
