# Generated by Django 5.2.9 on 2025-12-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_orderdetail_height_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neworder",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=11,
                null=True,
                verbose_name="Cost price of order",
            ),
        ),
        migrations.AlterField(
            model_name="neworder",
            name="profit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=11,
                null=True,
                verbose_name="Profit from the order",
            ),
        ),
        migrations.AlterField(
            model_name="neworder",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=11,
                null=True,
                verbose_name="Order's total price",
            ),
        ),
    ]
