# Generated by Django 5.2.9 on 2025-12-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
        ("orders", "0004_alter_neworder_cost_price_alter_neworder_profit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderdetail",
            old_name="include_waster_percentage",
            new_name="include_waste_percentage",
        ),
        migrations.AddField(
            model_name="order",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_related",
                to="orders.orderdetail",
                verbose_name="Related order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="handle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="materials.handletype",
                verbose_name="Order's handle type",
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="has_handle",
            field=models.BooleanField(default=False, verbose_name="Order has handle"),
        ),
    ]
