# Generated by Django 5.2.9 on 2025-12-23 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_master"),
        (
            "orders",
            "0005_rename_include_waster_percentage_orderdetail_include_waste_percentage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="neworder",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_order",
                to="company.company",
                verbose_name="Company order",
            ),
            preserve_default=False,
        ),
    ]
