# Generated by Django 5.2.9 on 2025-12-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_neworder_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("ALUMIN", "Alumin"),
                    ("PLAST", "Plast"),
                    ("THERMO", "Thermo"),
                ],
                default="ALUMIN",
                max_length=32,
                verbose_name="Order's material type",
            ),
            preserve_default=False,
        ),
    ]
