# Generated by Django 5.2.9 on 2025-12-05 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+998\\d{9}$")
                ],
                verbose_name="Phone number",
            ),
        ),
    ]
