# Generated by Django 5.2.9 on 2025-12-07 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Employee's full name.",
                        max_length=64,
                        verbose_name="Full name",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+998\\d{9}$"
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("ORDER_RECIPIENT", "Order_recipient"),
                            ("COLLECTOR", "Collector"),
                            ("INSTALLER", "Installer"),
                            ("DRIVER", "Driver"),
                            ("GLASS_CUTTER", "Glass_cutter"),
                        ],
                        max_length=64,
                        verbose_name="Employee profession",
                    ),
                ),
                (
                    "share",
                    models.FloatField(
                        help_text="Employee's share", verbose_name="Share"
                    ),
                ),
                (
                    "total_share",
                    models.FloatField(
                        help_text="Total of employee's shares",
                        verbose_name="Total share",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
    ]
