# Generated by Django 5.2.9 on 2025-12-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="total_share",
            field=models.FloatField(
                blank=True,
                help_text="Total of employee's shares",
                null=True,
                verbose_name="Total share",
            ),
        ),
    ]
