# Generated by Django 5.2.9 on 2025-12-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_employee_total_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="total_share",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total of employee's shares",
                max_digits=11,
                null=True,
                verbose_name="Total share",
            ),
        ),
    ]
