# Generated by Django 5.2.9 on 2025-12-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_employee_total_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="paid_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=11,
                null=True,
                verbose_name="Paid salary",
            ),
        ),
    ]
