# Generated by Django 5.2.9 on 2025-12-08 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_employee_paid_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="paid_salary",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="total_share",
        ),
        migrations.CreateModel(
            name="EmployeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=11, verbose_name="Amount"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts.employee",
                        verbose_name="Related employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Payment",
                "verbose_name_plural": "Employee Payments",
            },
        ),
    ]
