# Generated by Django 5.2.9 on 2025-12-05 05:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Dealer name")),
            ],
            options={
                "verbose_name": "Dealer",
                "verbose_name_plural": "Dealers",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Provider name"
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/logo",
                        verbose_name="Provider logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "free_delivery",
                    models.BooleanField(default=True, verbose_name="Free delivery"),
                ),
                (
                    "telegram_link",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Telegram group link",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.district",
                        verbose_name="Company district",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.region",
                        verbose_name="Company region",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="company.dealer",
                        verbose_name="Company dealer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="ProductConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("ALUMIN", "Alumin"),
                            ("PLAST", "Plast"),
                            ("THERMO", "Thermo"),
                        ],
                        max_length=32,
                        verbose_name="Product type",
                    ),
                ),
                (
                    "is_in_percentage",
                    models.BooleanField(
                        default=True, verbose_name="Profit by percentage"
                    ),
                ),
                (
                    "is_in_meter",
                    models.BooleanField(default=False, verbose_name="Profit by meter"),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.0"),
                        max_digits=6,
                        verbose_name="Profit amount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="company.company",
                        verbose_name="Related company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.currency",
                        verbose_name="Profit currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product configuration",
                "verbose_name_plural": "Product configurations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "product_type"),
                        name="unique_company_product_type",
                    )
                ],
            },
        ),
    ]
